export const THREAT_LABELS = {
  unknown: "信息不足",
  chicken: "鸡胡／普通牌型",
  mixedFlush: "混一色倾向",
  pureFlush: "清一色倾向",
  triplets: "对对胡倾向",
  honors: "字牌大牌倾向",
};

export const SUIT_LABELS = {
  unknown: "未判断",
  m: "万子",
  p: "筒子",
  s: "条子",
  z: "字牌",
};

const discardModes = (length, drawIndexes = []) => {
  const draws = new Set(drawIndexes);
  return Array.from({ length }, (_, index) => (draws.has(index) ? "draw" : "hand"));
};

export const questions = [
  {
    id: "Q001",
    title: "晚巡路线转折：大牌、对对胡与鸡胡",
    round: "东 2",
    wallRemaining: 47,
    prompt: "第11巡刚摸入八条。只根据公开牌面，哪张牌的综合预期损失最低？",
    hint: "对家第10巡首次手切筒子；下家连续两巡手切目标附近牌；上家虽可能听牌，但鸡胡不能接炮。",
    answerTile: "4m",
    candidates: ["P", "7p", "4m", "7s"],
    self: {
      wind: "S",
      hand: ["2m", "3m", "4m", "5m", "6m", "2p", "3p", "4p", "7p", "3s", "4s", "7s", "P", "8s"],
      river: ["W", "1s", "9s", "1m", "9p", "2p", "5s", "N"],
      discardModes: discardModes(8, [3, 5]),
      drawnIndex: 13,
    },
    opponents: {
      left: {
        label: "上家",
        wind: "E",
        threat: "chicken",
        focusSuit: "unknown",
        readyLikelihood: 0.004183405823566519,
        valueWeight: 2,
        openCount: 0,
        river: ["W", "9s", "1p", "9m", "S", "5p", "2s", "N", "P", "9p"],
        discardModes: discardModes(10, [1, 2, 3, 6, 8]),
        melds: [],
        passedTiles: [],
      },
      top: {
        label: "对家",
        wind: "N",
        threat: "honors",
        focusSuit: "p",
        readyLikelihood: 0.04205802518928599,
        valueWeight: 20,
        openCount: 6,
        river: ["1p", "9p", "9m", "7m", "1s", "4m", "9s", "N", "8m", "3p"],
        discardModes: discardModes(10, [0, 1, 3, 5, 8]),
        melds: [
          { type: "碰", tiles: ["C", "C", "C"] },
          { type: "碰", tiles: ["F", "F", "F"] },
        ],
        passedTiles: [],
      },
      right: {
        label: "下家",
        wind: "W",
        threat: "triplets",
        focusSuit: "unknown",
        readyLikelihood: 0.05726987436962096,
        valueWeight: 4,
        openCount: 6,
        river: ["6p", "W", "1p", "9p", "7p", "1m", "8p", "6s"],
        discardModes: discardModes(8, [2, 4]),
        melds: [
          { type: "碰", tiles: ["E", "E", "E"] },
          { type: "碰", tiles: ["2s", "2s", "2s"] },
        ],
        passedTiles: [],
      },
    },
    evidence: [
      { label: "转折", text: "对家第10巡首次手切三筒，听牌信号增强" },
      { label: "副露", text: "对家碰中、发；下家碰东、二条" },
      { label: "鸡胡", text: "上家可能听四万，但鸡胡只能自摸" },
    ],
    explanation:
      "C 四万。公开信息模型下，四万的特殊牌型接炮概率和预期损失最低。固定暗手中，上家确实听四万，但只构成鸡胡，不能荣和；A 白、B 七筒分别放给对家的大／小三元叠加牌型，D 七条放给下家的对对胡。",
    candidateNotes: {
      P: "对家的三元牌大牌方向",
      "7p": "进入对家的筒子混一色方向",
      "4m": "上家仅鸡胡等待，不能接炮",
      "7s": "下家的对对胡等待",
    },
    candidateOverrides: {
      P: {
        probability: 0.0035292519348015805,
        expectedLoss: 0.05662460440802392,
        summary: "主要危险对象：对家；常见牌型为混一色＋小三元",
      },
      "7p": {
        probability: 0.005091517692306979,
        expectedLoss: 0.026812768747676505,
        summary: "主要危险对象：对家；进入筒子混一色方向",
      },
      "4m": {
        probability: 0.00021235759885451788,
        expectedLoss: 0.0019976575736073555,
        summary: "特殊牌型接炮概率最低；上家鸡胡不能荣和",
      },
      "7s": {
        probability: 0.00043313941976586,
        expectedLoss: 0.0027890323550752005,
        summary: "下家对对胡路线仍需防范",
      },
    },
    source: {
      method: "完整136张回放＋公开信息加权蒙特卡洛V0",
      ruleVersion: "GD-DEF-V1",
      sampleCount: 30000,
    },
  },
  {
    id: "pass-window",
    title: "过胡窗口与主要威胁",
    round: "南 2",
    wallRemaining: 48,
    prompt: "现在轮到你出牌，哪一张的综合风险最低？",
    hint: "上家的牌型信号最强，但另外两家仍可能以鸡胡听牌。",
    answerTile: "4m",
    candidates: ["1p", "W", "4m", "6p"],
    self: {
      wind: "S",
      hand: ["2m", "3m", "4m", "5m", "6m", "7m", "1p", "6p", "7p", "8p", "1s", "2s", "3s", "W"],
      river: ["9p", "1p", "8m", "W", "6s", "2m", "8p", "S", "4m", "6p"],
      discardModes: discardModes(10, [2, 5, 8]),
      drawnIndex: 13,
    },
    opponents: {
      left: {
        label: "上家",
        wind: "E",
        threat: "mixedFlush",
        focusSuit: "p",
        readyLikelihood: 0.82,
        valueWeight: 4.8,
        openCount: 6,
        river: ["9m", "2s", "E", "7m", "5s", "F", "3m", "9s", "1m", "N", "8s"],
        discardModes: discardModes(11, [0, 4, 7]),
        melds: [
          { type: "碰", tiles: ["7p", "7p", "7p"] },
          { type: "碰", tiles: ["C", "C", "C"] },
        ],
        passedTiles: [{ tile: "4m", active: true }],
      },
      top: {
        label: "对家",
        wind: "N",
        threat: "chicken",
        focusSuit: "unknown",
        readyLikelihood: 0.27,
        valueWeight: 2,
        openCount: 3,
        river: ["1m", "9p", "E", "2s", "8m", "P", "4p", "6s", "3m", "C", "9s", "2p"],
        discardModes: discardModes(12, [1, 5, 9]),
        melds: [{ type: "碰", tiles: ["5s", "5s", "5s"] }],
        passedTiles: [],
      },
      right: {
        label: "下家",
        wind: "W",
        threat: "unknown",
        focusSuit: "unknown",
        readyLikelihood: 0.23,
        valueWeight: 2.2,
        openCount: 0,
        river: ["P", "9m", "1s", "6m", "2p", "S", "8s", "4p", "7m", "3s", "E", "5m"],
        discardModes: discardModes(12, [2, 6, 10]),
        melds: [],
        passedTiles: [],
      },
    },
    evidence: [
      { label: "关键事件", text: "上家本轮已过 4万，之后尚未摸牌" },
      { label: "副露", text: "上家碰出 7筒与红中，混一色信号较强" },
      { label: "提醒", text: "自己打过的牌不构成永久安全" },
    ],
    explanation:
      "4万对当前最危险的上家处于有效过胡窗口，因此这一家暂时不能胡4万。对家与下家仍保留普通听牌风险，所以它不是“全桌永远安全”，但综合点炮概率与损失仍最低。1筒和6筒正好进入上家的筒子主色；西风虽然不在主色内，仍可能成为混一色的字牌搭子。",
    candidateNotes: {
      "1p": "进入上家混一色主色",
      W: "字牌可参与混一色",
      "4m": "主要威胁处于过胡锁定",
      "6p": "主色中张，兼容等待较多",
    },
  },
  {
    id: "messy-river",
    title: "不干净的牌河与转型信号",
    round: "南 3",
    wallRemaining: 34,
    prompt: "牌河并不“标准”，现在应优先打哪张？",
    hint: "有人可能中途转型，也有人只是安静地听一手普通鸡胡。",
    answerTile: "9s",
    candidates: ["5p", "C", "9s", "3m"],
    self: {
      wind: "S",
      hand: ["2m", "3m", "3m", "4m", "5m", "5p", "6p", "7p", "8p", "9s", "9s", "C", "C", "3m"],
      river: ["F", "S", "3s", "W", "1m", "1s", "4s", "5s", "6s", "8s", "9p"],
      discardModes: discardModes(11, [1, 4, 8]),
      drawnIndex: 13,
    },
    opponents: {
      left: {
        label: "上家",
        wind: "E",
        threat: "triplets",
        focusSuit: "unknown",
        readyLikelihood: 0.68,
        valueWeight: 4.1,
        openCount: 6,
        river: ["1p", "6p", "2s", "9m", "3p", "E", "8m", "4p", "7s", "2m", "P", "6s", "5m"],
        discardModes: discardModes(13, [0, 5, 9, 12]),
        melds: [
          { type: "碰", tiles: ["8p", "8p", "8p"] },
          { type: "碰", tiles: ["N", "N", "N"] },
        ],
        passedTiles: [],
      },
      top: {
        label: "对家",
        wind: "N",
        threat: "chicken",
        focusSuit: "unknown",
        readyLikelihood: 0.74,
        valueWeight: 2,
        openCount: 0,
        river: ["E", "P", "1m", "9p", "2s", "8s", "4m", "7p", "6m", "1s", "W", "5s", "2p"],
        discardModes: discardModes(13, [2, 6, 10]),
        melds: [],
        passedTiles: [{ tile: "9s", active: true }],
      },
      right: {
        label: "下家",
        wind: "W",
        threat: "mixedFlush",
        focusSuit: "m",
        readyLikelihood: 0.58,
        valueWeight: 3.8,
        openCount: 3,
        river: ["9m", "1p", "E", "2p", "7m", "4s", "3s", "5m", "2s", "P", "6p", "N", "7s"],
        discardModes: discardModes(13, [1, 7, 11]),
        melds: [{ type: "碰", tiles: ["6m", "6m", "6m"] }],
        passedTiles: [],
      },
    },
    evidence: [
      { label: "转型", text: "上家早段打过筒子，之后连续碰牌转向对对胡" },
      { label: "隐蔽威胁", text: "对家没有副露，但后段舍牌已经收紧" },
      { label: "过胡", text: "对家刚刚放过 9条，尚未再次摸牌" },
    ],
    explanation:
      "不能因为上家的早期牌河杂乱，就否定他后来转成对对胡；也不能只盯着副露最多的人。对家是高概率的普通听牌，但9条正处于他的有效过胡窗口；它同时不进入下家的万子混一色方向，对上家的对对胡兼容度也较低，因此综合最低。",
    candidateNotes: {
      "5p": "普通鸡胡兼容度高",
      C: "对对胡与混一色都可用字牌",
      "9s": "主要鸡胡威胁已过，且远离万子主色",
      "3m": "进入下家的万子方向",
    },
  },
  {
    id: "liability-loss",
    title: "包三家与预期损失",
    round: "南 4",
    wallRemaining: 22,
    prompt: "哪张不一定“最不容易点”，却能让预期损失最低？",
    hint: "概率只是一半；当对手已经9张落地，大牌方向的点炮代价会被放大。",
    answerTile: "7s",
    candidates: ["E", "7s", "5m", "2p"],
    self: {
      wind: "S",
      hand: ["3m", "4m", "5m", "6m", "7m", "2p", "3p", "4p", "6s", "7s", "8s", "E", "E", "7s"],
      river: ["9s", "W", "1m", "2p", "6m", "7p", "S", "4s", "5s", "P", "3s", "8p"],
      discardModes: discardModes(12, [2, 6, 9]),
      drawnIndex: 13,
    },
    opponents: {
      left: {
        label: "上家",
        wind: "E",
        threat: "honors",
        focusSuit: "z",
        readyLikelihood: 0.88,
        valueWeight: 8.5,
        openCount: 9,
        river: ["1m", "9m", "3p", "8p", "3s", "7s", "4m", "6p", "2s", "9p", "5m", "1s", "8m"],
        discardModes: discardModes(13, [0, 4, 8, 12]),
        melds: [
          { type: "碰", tiles: ["C", "C", "C"] },
          { type: "碰", tiles: ["F", "F", "F"] },
          { type: "碰", tiles: ["N", "N", "N"] },
        ],
        passedTiles: [],
      },
      top: {
        label: "对家",
        wind: "N",
        threat: "chicken",
        focusSuit: "unknown",
        readyLikelihood: 0.61,
        valueWeight: 2,
        openCount: 0,
        river: ["P", "9s", "1p", "8m", "2s", "7p", "3m", "6s", "W", "4p", "9m", "2m", "C"],
        discardModes: discardModes(13, [1, 5, 9]),
        melds: [],
        passedTiles: [],
      },
      right: {
        label: "下家",
        wind: "W",
        threat: "unknown",
        focusSuit: "unknown",
        readyLikelihood: 0.39,
        valueWeight: 2.4,
        openCount: 3,
        river: ["9p", "1s", "E", "8p", "2m", "7m", "P", "3s", "6p", "4m", "N", "1p", "8s"],
        discardModes: discardModes(13, [3, 7, 10]),
        melds: [{ type: "碰", tiles: ["5p", "5p", "5p"] }],
        passedTiles: [],
      },
    },
    evidence: [
      { label: "高损失", text: "上家三组字牌已9张落地，继续喂牌需计包三家风险" },
      { label: "牌型", text: "大三元／字一色方向尚未完全排除" },
      { label: "取舍", text: "比较的是概率 × 可能损失，而非只看点炮率" },
    ],
    explanation:
      "东风的原始点炮概率未必是四张中最高，但一旦喂给已9张落地的上家，潜在番值与包三家责任会显著放大预期损失。7条在上家的牌河中已经出现，且不符合字牌大牌方向；它对另外两家的普通等待仍有风险，但综合代价最低。",
    candidateNotes: {
      E: "字牌大牌方向，且触发高损失责任",
      "7s": "远离主要大牌方向，牌河亦有弱化信号",
      "5m": "普通鸡胡兼容度较高",
      "2p": "上家打过但另外两家仍可等待",
    },
  },
];

