export const TILE_IMAGE_URLS = Object.freeze({
  E: "assets/tiles/01-E-east.png",
  S: "assets/tiles/02-S-south.png",
  W: "assets/tiles/03-W-west.png",
  N: "assets/tiles/04-N-north.png",
  P: "assets/tiles/05-P-white-dragon.png",
  F: "assets/tiles/06-F-green-dragon.png",
  C: "assets/tiles/07-C-red-dragon.png",
  "1m": "assets/tiles/08-1m.png",
  "2m": "assets/tiles/09-2m.png",
  "3m": "assets/tiles/10-3m.png",
  "4m": "assets/tiles/11-4m.png",
  "5m": "assets/tiles/12-5m.png",
  "6m": "assets/tiles/13-6m.png",
  "7m": "assets/tiles/14-7m.png",
  "8m": "assets/tiles/15-8m.png",
  "9m": "assets/tiles/16-9m.png",
  "1p": "assets/tiles/17-1p.png",
  "2p": "assets/tiles/18-2p.png",
  "3p": "assets/tiles/19-3p.png",
  "4p": "assets/tiles/20-4p.png",
  "5p": "assets/tiles/21-5p.png",
  "6p": "assets/tiles/22-6p.png",
  "7p": "assets/tiles/23-7p.png",
  "8p": "assets/tiles/24-8p.png",
  "9p": "assets/tiles/25-9p.png",
  "1s": "assets/tiles/26-1s.png",
  "2s": "assets/tiles/27-2s.png",
  "3s": "assets/tiles/28-3s.png",
  "4s": "assets/tiles/29-4s.png",
  "5s": "assets/tiles/30-5s.png",
  "6s": "assets/tiles/31-6s.png",
  "7s": "assets/tiles/32-7s.png",
  "8s": "assets/tiles/33-8s.png",
  "9s": "assets/tiles/34-9s.png",
});

export function tileImageUrl(tile) {
  return TILE_IMAGE_URLS[tile] ?? "";
}
