export const TILE_IMAGE_URLS = Object.freeze({
  E: "assets/tiles-webp/01-E-east.webp",
  S: "assets/tiles-webp/02-S-south.webp",
  W: "assets/tiles-webp/03-W-west.webp",
  N: "assets/tiles-webp/04-N-north.webp",
  P: "assets/tiles-webp/05-P-white-dragon.webp",
  F: "assets/tiles-webp/06-F-green-dragon.webp",
  C: "assets/tiles-webp/07-C-red-dragon.webp",
  "1m": "assets/tiles-webp/08-1m.webp",
  "2m": "assets/tiles-webp/09-2m.webp",
  "3m": "assets/tiles-webp/10-3m.webp",
  "4m": "assets/tiles-webp/11-4m.webp",
  "5m": "assets/tiles-webp/12-5m.webp",
  "6m": "assets/tiles-webp/13-6m.webp",
  "7m": "assets/tiles-webp/14-7m.webp",
  "8m": "assets/tiles-webp/15-8m.webp",
  "9m": "assets/tiles-webp/16-9m.webp",
  "1p": "assets/tiles-webp/17-1p.webp",
  "2p": "assets/tiles-webp/18-2p.webp",
  "3p": "assets/tiles-webp/19-3p.webp",
  "4p": "assets/tiles-webp/20-4p.webp",
  "5p": "assets/tiles-webp/21-5p.webp",
  "6p": "assets/tiles-webp/22-6p.webp",
  "7p": "assets/tiles-webp/23-7p.webp",
  "8p": "assets/tiles-webp/24-8p.webp",
  "9p": "assets/tiles-webp/25-9p.webp",
  "1s": "assets/tiles-webp/26-1s.webp",
  "2s": "assets/tiles-webp/27-2s.webp",
  "3s": "assets/tiles-webp/28-3s.webp",
  "4s": "assets/tiles-webp/29-4s.webp",
  "5s": "assets/tiles-webp/30-5s.webp",
  "6s": "assets/tiles-webp/31-6s.webp",
  "7s": "assets/tiles-webp/32-7s.webp",
  "8s": "assets/tiles-webp/33-8s.webp",
  "9s": "assets/tiles-webp/34-9s.webp",
});

export function tileImageUrl(tile) {
  return TILE_IMAGE_URLS[tile] ?? "";
}
